### ISSUE TITLE
pwwka connection handling strategy

### ISSUE THREAD

**Issue by joshuaflanagan** [stitchfix/pwwka#37]
I've noticed that the `Pwwka::Transmitter` opens and closes a RabbitMQ connection for every message it sends. This seems counter to the guidance from the bunny documentation, and the fact that RabbitMQ has the concept of long-lived connections with multiplexed channels within a connection.

From [the bunny guide on connecting from web applications](http://rubybunny.info/articles/connecting.html#connecting_in_web_applications_ruby_on_rails_sinatra_etc):

> Channels are typically long lived: you open one or more of them and use them for a period of time, as opposed to opening a new channel for each published message, for example.

and

> When connecting in Web apps, the rule of thumb is: do it in an initializer, not controller actions or request handlers.

I am wondering what led to the decision to create and close the TCP connection for every message. Did you run into specific issues when trying to keep a long-lived connection or channel? Any insight into this approach would be greatly appreciated.

**Comment by davetron5000** [comment]
@nickflux you wrote the initial version of this…any ideas?

**Comment by nickflux** [comment]
I'm afraid I can't remember, it was so long ago. It's possible that there is no good reason and it would be good to look at the alternative.

**Comment by davetron5000** [comment]
Pwwka now has some integration tests, so if someone wants to look into this, it should be doable.  This isn't causing us problems ATM so we likely won't address this.  PRs absolutely welcome, though.
