### ISSUE TITLE
SignalException from message_handler:receive

### ISSUE THREAD

**Issue by nwochaadim** [stitchfix/pwwka#68]
We are getting a `SIGTERM SignalException` while running Pwwka using a worker dyno on Heroku. This occurs periodically even when the dyno is not restarted or reconfigured.

Here is some stack trace:

<img width="843" alt="screen shot 2018-06-22 at 11 59 36 pm" src="https://user-images.githubusercontent.com/16139143/41802434-88a58b2c-7678-11e8-8e27-a36fe27c6785.png">

**Comment by davetron5000** [comment]
Heroku kills dynos daily - that could be what's happening here.  We saw this frequently while on Heroku.  Are you seeing it more than once a day?

**Comment by nwochaadim** [comment]
Right, that explains it. The errors actually occur daily. Thanks @davetron5000
