### ISSUE TITLE
Parse other schemas as payload

### ISSUE THREAD

**Issue by igbanam** [stitchfix/pwwka#69]
I recently came across a scenario where Pwwka broke before getting to my handler. I would later realize that we have assumed all data coming through the queues would be JSON. Pwwka also shares this assumption here https://github.com/stitchfix/pwwka/blob/master/lib/pwwka/receiver.rb#L27 

Could we possibly make pwwka listen for other schemas? XML is particular case.

I think JSON and XML cover a prettu wide spectrum of apps which would use Pwwka.

**Comment by davetron5000** [comment]
It would be easy to add this as a global configuration (e.g. "all messages are XML").  A bit trickier to handle arbitrary encodings.  We don't use XML for anything so we would not be in a good position to figure out what the right thing is to do, but if you want to work up an implementation for discussion that might be best?

**Comment by igbanam** [comment]
@davetron5000 I see this has been merged. Awesome 🙌 

I see that there are some errors though with TravisCI since this was merged. Is this due to code I wrote? Is there anyway I could help with this?

**Comment by davetron5000** [comment]
Nope, it's all good. Travis build has been borked for a while, which Irealize is not great for non-Stitch Fixers, but we run the build internally on Circle CI and it's all 💚 so you should be good to go
